name: Generate Design Tokens

on:
  push:
    branches:
      - main # Or your main development branch (e.g., 'master', 'develop')
    paths:
      - 'tokens/**' # Trigger when any file in the 'tokens' directory changes
      - 'config/style-dictionary.config.js' # Trigger if the config changes

permissions:
  contents: write

jobs:
  build_and_commit_tokens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a Node.js version compatible with Style Dictionary

      - name: Install dependencies
        run: npm ci # Use 'npm ci' for clean installs in CI environments

      - name: Build Design Tokens
        run: npm run build:tokens # Executes the script defined in package.json

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5 # Action to automatically commit changes
        with:
          commit_message: '🎨 chore(tokens): Auto-generated design tokens from Figma [skip ci]' # Meaningful commit message
          file_pattern: |
            src/styles/_tokens.scss
            src/styles/tokens.css
            src/ts/tokens.ts
            src/ts/font-tokens.ts
          # No need to set 'github_token' usually, as GITHUB_TOKEN has permissions for current repo
          # This action defaults to using GITHUB_TOKEN, which is often sufficient for committing to the same repo.

# NOTE: If you have branch protection rules that prevent direct pushes to 'main',
# this workflow will fail to push. In that case, consider using a pull request-based workflow.